version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nprl
      POSTGRES_PASSWORD: nprl
      POSTGRES_DATABASE: nprl
      POSTGRES_ROOT_PASSWORD: nprl
      pgdata: data-pstgresql
    ports:
      - "5432:5432"
    volumes:
#      - data-pstgresql:/data
      - ./posgresql:/docker-entrypoint-initdb.d

  web:
    restart: always
    environment:
      POSGRESQL-HOSTNAME: db
    container_name: api
    build:
      context: .
    ports:
      - "8000:5000"
    depends_on:
      - db