version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: univ_pr
      POSTGRES_PASSWORD: univ_pr
      POSTGRES_DATABASE: univ_pr
      POSTGRES_ROOT_PASSWORD: univ_pr
      pgdata: data-pstgresql
    ports:
      - "5432:5432"
    volumes:
      - ./posgresql:/docker-entrypoint-initdb.d

